config/routes.rb
Rails.application.routes.draw do
  resources :searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'searches#new'
end

app/models/api_auth.rb
class ApiAuth < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
require 'json'
require 'rest_client'


class Search < ApplicationRecord
  validates :query, presence: true


  def getQueryCount(aquery)
    Search.where(query: aquery).count
  end
  
  def getQueryDates(aquery)
    Search.select(:created_at).where(query: aquery)
  end
  
  def getQueryHistory(aquery)
    history = { 'count' => getQueryCount(aquery) }
    history['dates'] = getQueryDates(aquery)

    return history
  end
  
  def getRecent(order='query', start=0, page=0)
    count = 'count'
    query = :query
    created = 'max(searches.created_at)'
    orders = {'created' =>  created, 'query' => query,
              count => count}
    order = orders.fetch(order, created)

    if order == count
      return Search.group(query).count.
               sort_by{ | k, v | v }.reverse
    end

    Search.select(query,'max(searches.created_at)').group(query).
      order(order)
      # order(order).limit(10).offset(start)
  end
  
  def tvdbBase
    'https://api.thetvdb.com'
  end
  
  def tvLogin
    loginData = RestClient.post(tvdbBase + '/login',
                                {"apikey": ENV['SECRET_TVDB_API_KEY'],
                                 "username": ENV['SECRET_TVDB_USER'],
                                 "userkey": ENV['SECRET_TVDB_USER_KEY']}.to_json,
                                content_type: 'application/json')
    atoken = JSON.parse(loginData)['token']
    auth=ApiAuth.where(name: 'tvdb').first
    auth.auth = atoken
    auth.save
  end

  def getTvAuth
    if ApiAuth.where(name: 'tvdb').first.auth == ''
      tvLogin
    end

    return {Authorization: 'Bearer ' +
            ApiAuth.where(name: 'tvdb').first.auth}
  end


  def getTvEndpoint(endPoint, relogin = false)
    begin 
      if relogin then tvLogin end
      data = RestClient.get(tvdbBase + endPoint, getTvAuth)
      return JSON.parse(data)['data']
    rescue
      if relogin then return [] end
      getTvEndpoint(endPoint, true)
    end
  end


  def getResults(aquery)
    results = []
    series = 'series'
    search = '/search/' + series
    rawResults = getTvEndpoint(search + '?name=' + aquery)

    rawResults.each do | v |
      seriesId = '/' + series + '/' + String(v['id'])
      results.append(getTvEndpoint(seriesId))
      #seriesEpisodes = getTvEndpoint(seriesId + '/episodes')
    end
    
    return results
    # params = getTvEndpoint(search + '/params')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def doom
    render html: 'doom'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    get = request.get? ? request.GET : {}
    @aquery = get.fetch('query', '')
    @sort = get.fetch('sort', '')
    @recents = []
    @sortopts = ['created', 'query', 'count']

    @search = Search.new
    @ahistory = @search.getQueryHistory(@aquery)
    recentsRaw = @search.getRecent(@sort)
    # @token = @search.getTvAuth
    

    @urlquery = ERB::Util.url_encode(@aquery)
    recentsRaw.each do | v |
      @recents.append(@sort == 'count' ? v[0] : v.query)
    end

    if @aquery == '' then return end
    @seriesFound = @search.getResults(@urlquery)
  end

  # GET /searches/1/edit
  def edit
    redirect_to action: 'new' and return
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to action: 'new', query: @search.query }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { redirect_to action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    redirect_to action: 'new' and return
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvdbShadow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :query %>
    <%= form.text_field :query, id: :search_query %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.query %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>Search TVDB</h1>

<div class='search-left search-content' >
  <div class='search-result' >
  <%= render 'form', search: @search %>

  <p><%# @token %></p>
  <% if @aquery != '' %>
    search returned <%= @seriesFound.count %> results
      <div class='search-series-found' >
        <div class='search-results-headrow search-series' >
          <span class='search-results-header search-title' >Name</span>
          <span class='search-results-header search-series-date' >Start Date</span>
          <span class='search-results-header search-series-rating' >Rating</span>
        </div>
      <% @seriesFound.each do | series | %>
        <% @seriesLink = 'https://www.thetvdb.com/?tab=series&id=' + u(series['id']) %>
        <div class="search-series" onclick="window.open('<%= @seriesLink %>', '_blank')" >
          <span class='search-title' ><%= series['seriesName'] %></span>
          <span class='search-series-date' ><%= series['firstAired'] %></span>
          <span class='search-series-rating' ><%= series['rating'] %></span>
        </div>
      <% end %>
      </div>
    </div>
    <div class='search-right search-data' >
      <div class='search-label search-count-title' >
        <%= h @aquery %> has been searched 
        <%= @ahistory['count'] %> times
      </div>
      <div class='search-label search-date-title'>
        on these dates
      </div>
      <% @ahistory['dates'].each do | adate | %>
        <div class='search-dates' ><%= adate.created_at %></div>
      <% end %>
    </div>
  <% else %>
    </div>
  <% end %>
</div>

<div class='search-right search-history' >
  <div class = 'search-recents-sort' >
    sort by -
    <% @sortopts.each do | sort | %>
      <span>
        <a href=<%= new_search_path(query: @urlquery, sort: sort) %> >
          <%= sort %>
        </a>&nbsp
      </span>
    <% end %>
  </div>
  <% @recents.each do | recent | %>
    <div class='search-recent' >
      <% @htmlRecent = h(recent) %>
      <%= form_tag "/searches" do %>
        <%= hidden_field_tag 'search[query]', @htmlRecent %>
        <%= submit_tag @htmlRecent %>
      <% end %>
    </div>
  <% end %>
</div>

</div>

<%# link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @search.query %>
</p>

<%= link_to 'Back', searches_path %>